export const FamilyToSupport = () => ({
  data: [
    {
      family_name: "The Johnsons",
      phone: "09051352144",
      members_no: 4,
      location: 3,
      breadwinner_job: "Plumber",
      selected: 0,
      account_bank: "GTB",
      account_no: "0372883933",
      account_name: "Inobong Johnson",
      bvn: "",
      family_member_bvn: null,
      family_picture: "http://picture.com",
      full_address: "13, Ayoola Street, Bairga Lagos",
      total_amount_received: null,
      no_of_times_paid: 0,
      facial_recognition: 1,
      account_verified: 1,
      bvn_confirmed: 1,
      eligible: 1,
      location_match: 1,
      family_member_match: 1,
      amount_given: 5000
    },
    {
      family_name: "The Kalejaiyes",
      phone: "09023249494",
      members_no: 5,
      location: 5,
      breadwinner_job: "Farmer",
      selected: 0,
      account_bank: "Stanbic",
      account_no: "0032323233",
      account_name: "Joshua Kalejaiye",
      bvn: "",
      family_member_bvn: null,
      family_picture: "https://ldkd.com",
      full_address: "10 Modake Close Falujaye Street, Maryland, Lagos",
      total_amount_received: null,
      no_of_times_paid: 0,
      facial_recognition: 1,
      account_verified: 1,
      bvn_confirmed: 1,
      eligible: 1,
      location_match: 1,
      family_member_match: 1,
      amount_given: 5000
    },
    {
      family_name: "The Pocahontas",
      phone: "09051352145",
      members_no: 6,
      location: 2,
      breadwinner_job: "Trader",
      selected: 0,
      account_bank: "GTB",
      account_no: "0994242924",
      account_name: "Gbemi Pocahantas",
      bvn: "",
      family_member_bvn: null,
      family_picture: "https://psosf.csocs",
      full_address: "5, Folaranke street",
      total_amount_received: null,
      no_of_times_paid: 0,
      facial_recognition: 1,
      account_verified: 1,
      bvn_confirmed: 1,
      eligible: 1,
      location_match: 1,
      family_member_match: 1,
      amount_given: 5000
    }
  ],
  amount_to_charge: 15000,
  message:
    "We currently have fewer families that are eligible to receive your funds, so you will be charged lower than the amount you would have loved to give. Please feel free to send the remaining in the next hour.",
  status: true
});
